apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240201053116.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240201053116.0.0+build.02e9424
  releaseNotes: |
    Release v20240201053116.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-search-my-apps-bundle@sha256:b4602aaa9c30cfbf3311a4d04d6df6c3f2cc2bdcae97b48c6f9ce091d9224e38
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

