apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240201170044.0.0+build.6aff574
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240201170044.0.0+build.6aff574
  releaseNotes: |
    Release v20240201170044.0.0+build.6aff574 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-ui-my-apps-bundle@sha256:f82c47e2ad618206bc5c169344f55cdcbb1765a8997ec357e89c1b0ba355a644
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

