apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240131060737.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240131060737.0.0+build.02e9424
  releaseNotes: |
    Release v20240131060737.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-my-apps-bundle@sha256:117f618e5eaa3ce74aace25e8f7f5f5752dfdeb05e3375f8fb6f0bba71a11c89
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

