apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240201165436.0.0+build.c5ac160
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240201165436.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165436.0.0+build.c5ac160 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-search-proc-my-apps-bundle@sha256:30a68d4610624cf0df134a6e25f822466d23f5b23b9d76d79428214ab63521d2
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

