apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240201170106.0.0+build.6aff574
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240201170106.0.0+build.6aff574
  releaseNotes: |
    Release v20240201170106.0.0+build.6aff574 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-availability-my-apps-bundle@sha256:65146d317a7b2a78e9f4835c737b496624b9c2c4a9351aeed6c6ab1b7a1f7173
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

