apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240131060711.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240131060711.0.0+build.02e9424
  releaseNotes: |
    Release v20240131060711.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-31-01-2024-05-35-09-541803682/where-for-dinner-notify-my-apps-bundle@sha256:9d3a604dc7034035b1b3c6d035d5202abdd6e21cbaa5d94d2e15f7d85c8947a1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

